### PR TITLE
Add admin user as possible authors

### PR DESCRIPTION
**Pull request by maxraab**
Admin users could create issues in every project.

### CODE REVIEW

**Comment by nounder** [comment]
Would you be able to use single database query for that?

**Comment by maxraab** [comment]
I will have a look.

**Comment by maxraab** [comment]
@rgtk We could simplify it by using only one query :-) I've updated the PR.

**Comment by nounder** [comment]
The problem now is that we have to fetch all users and construct objects for them which is unnecessary and risky. We can try implement this by using code from `Project#users` and incorporate OR into the it.

Compatibility with Redmine 2.x is required.

**Comment by maxraab** [comment]
Jep, I understand.
Please take a look at the current version of the PR.

**Comment by nounder** [comment]
Looks alright. Thank you.

**Pull request merged**
