### PR TITLE
Sort authors by name

### PR DESCRIPTION
**Pull request by dchaib**
I have added some code to sort the authors alphabetically, which is very useful when you have a long list of authors.
I'm not an expert in Ruby, but it does the job.

### CODE REVIEW

**Comment by nounder** [comment]
Your ruby-foo is good but we can improve it a little bit. Instead of sorting it directly in the app, we can ask database to do it for us. Just add `sorted` to method chain after `project.users` and `User.active`.

**Comment by dchaib** [comment]
Thanks for the reply. These are actually my first ever lines of Ruby so improvements were expected! I'm glad you suggest them, but I'm afraid you could reach my limits fast!

I have looked for `sorted` but I have only found `order`.

Are you suggesting this?
```rb
project.users.order(:name)
```
```rb
User.active.joins(members: :roles).distinct(:id)
           .where("#{MemberRole.table_name}.role_id IN (?) OR #{User.table_name}.admin = ?", role_ids, true)
           .order(:name)
```

**Comment by nounder** [comment]
You couldn't find `sorted` method because it is not explicitly defined as method ([DuckDuckGo](https://duckduckgo.com/) "ruby metaprogramming" for more). Look for line with `scope :sorted` in file for `User` (`app/models/user.rb` in Redmine source); it defines `sorted` method at runtime so you can use it for `User` object or relations that are related to this model (`project.users` and `User.active` return these relations).

Now, my first message should be clear :)

**Comment by dchaib** [comment]
I think it is clear... Is my new proposal what you had in mind?

**Comment by nounder** [comment]
Good job! Thank you, Damien :)

**Pull request merged**
